version: '2.2'

services:
  gatsby:
    build: .
    entrypoint: sleep 14400
    volumes:
      - "./:/srv/www"
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - ".env.development"
      - ".env.production"
